function [header] = GetHeader()

    header.magicWord        = zeros(4);
    header.platform         = 0x0A2243;
    header.version          = zeros(1);
    header.totalPacketLen   = zeros(1);
    header.packetNumber     = zeros(1);
    header.timeCpuCycles    = zeros(1);
    header.radarID          = zeros(1);
    header.spmVersion       = zeros(1);
    header.trkVersion       = zeros(1);
    header.numTLVs          = zeros(1);
    header.type0            = zeros(1);
    header.length0          = zeros(1);
    header.address0         = zeros(1);
    header.type1            = zeros(1);
    header.length1          = zeros(1);
    header.address1         = zeros(1);
    header.type2            = zeros(1);
    header.length2          = zeros(1);
    header.address2         = zeros(1);
    header.type3            = zeros(1);
    header.length3          = zeros(1);
    header.address3         = zeros(1);
    header.type4            = zeros(1);
    header.length4          = zeros(1);
    header.address4         = zeros(1);
    header.type5            = zeros(1);
    header.length5          = zeros(1);
    header.address5         = zeros(1);
    header.platCode         = 3;
    header.sampleTimeMs     = 50;
end